spring:
    application:
        name: javapilot

server:       # Note that the port MUST be 80 to work in SC cloud!
  port: 8092  # Note that the port SHOULD NOT be 80 to work locally.
  #port: 80    # Use for SC cloud deployment!

javapilot:
    name: kobayashi  # Id of this simulator. Should be unique.
    relayUrl: ws://localhost:8080/ws/rest/messages # Address of relay on local host
    trainingUrl: http://localhost:8080/ws/rest/raceTracks/training # URL to start a training
    accessCode: kobayashi # the access code provided by the race management at registration

    #relayUrl:  ws://relay2.beta.swisscloud.io/ws/rest/messages # Address of relay in SC cloud !
